/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package happyburger1;


import java.awt.Color;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;

/**
 *
 * @author damha
 */
public class Dashboard extends javax.swing.JFrame {
    private JDesktopPane desktopPane;

    /**
     * Creates new form Dashboard
     */
    Color DefaultColor,ClickedColor;
    public Dashboard() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        DefaultColor = new Color (242,242,242);
        ClickedColor = new Color (230,235,240);
        
        //set default color to pan on run time
        pnmenu.setBackground(DefaultColor);
        pncust.setBackground(DefaultColor);
        pnpesanan.setBackground(DefaultColor);
        pnpegawai.setBackground(DefaultColor);
        pnmeja.setBackground(DefaultColor);
        pntransaksi.setBackground(DefaultColor);
        pndetailpesanan.setBackground(DefaultColor);
        
        
        
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnmenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnpesanan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pncust = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnpegawai = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnmeja = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pntransaksi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pndetailpesanan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        utama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(874, 639));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HappyBurger", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        pnmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnmenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnmenuMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Menu");

        javax.swing.GroupLayout pnmenuLayout = new javax.swing.GroupLayout(pnmenu);
        pnmenu.setLayout(pnmenuLayout);
        pnmenuLayout.setHorizontalGroup(
            pnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnmenuLayout.setVerticalGroup(
            pnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnpesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnpesananMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnpesananMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Pesanan");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnpesananLayout = new javax.swing.GroupLayout(pnpesanan);
        pnpesanan.setLayout(pnpesananLayout);
        pnpesananLayout.setHorizontalGroup(
            pnpesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpesananLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
        );
        pnpesananLayout.setVerticalGroup(
            pnpesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pncust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pncustMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pncustMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Customer");

        javax.swing.GroupLayout pncustLayout = new javax.swing.GroupLayout(pncust);
        pncust.setLayout(pncustLayout);
        pncustLayout.setHorizontalGroup(
            pncustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pncustLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pncustLayout.setVerticalGroup(
            pncustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pncustLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnpegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnpegawaiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnpegawaiMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Pegawai");

        javax.swing.GroupLayout pnpegawaiLayout = new javax.swing.GroupLayout(pnpegawai);
        pnpegawai.setLayout(pnpegawaiLayout);
        pnpegawaiLayout.setHorizontalGroup(
            pnpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpegawaiLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnpegawaiLayout.setVerticalGroup(
            pnpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnmeja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnmejaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnmejaMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Meja");

        javax.swing.GroupLayout pnmejaLayout = new javax.swing.GroupLayout(pnmeja);
        pnmeja.setLayout(pnmejaLayout);
        pnmejaLayout.setHorizontalGroup(
            pnmejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmejaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnmejaLayout.setVerticalGroup(
            pnmejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnmejaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        pntransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pntransaksiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pntransaksiMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Transaksi");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pntransaksiLayout = new javax.swing.GroupLayout(pntransaksi);
        pntransaksi.setLayout(pntransaksiLayout);
        pntransaksiLayout.setHorizontalGroup(
            pntransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntransaksiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pntransaksiLayout.setVerticalGroup(
            pntransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pndetailpesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pndetailpesananMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pndetailpesananMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Detail Pesanan");

        javax.swing.GroupLayout pndetailpesananLayout = new javax.swing.GroupLayout(pndetailpesanan);
        pndetailpesanan.setLayout(pndetailpesananLayout);
        pndetailpesananLayout.setHorizontalGroup(
            pndetailpesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pndetailpesananLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        pndetailpesananLayout.setVerticalGroup(
            pndetailpesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndetailpesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(pndetailpesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pntransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnpesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnmeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pncust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pncust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnpesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnpegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnmeja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pntransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pndetailpesanan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1701670781003.png"))); // NOI18N

        javax.swing.GroupLayout utamaLayout = new javax.swing.GroupLayout(utama);
        utama.setLayout(utamaLayout);
        utamaLayout.setHorizontalGroup(
            utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utamaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        utamaLayout.setVerticalGroup(
            utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utamaLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnmenuMousePressed
        // TODO add your handling code here:
        pnmenu.setBackground(ClickedColor);
        pncust.setBackground(DefaultColor);
        
        pnpesanan.setBackground(DefaultColor);
        pnpegawai.setBackground(DefaultColor);
        pnmeja.setBackground(DefaultColor);
        pntransaksi.setBackground(DefaultColor);
        pndetailpesanan.setBackground(DefaultColor);
        
    }//GEN-LAST:event_pnmenuMousePressed

    private void pnmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnmenuMouseClicked
        // TODO add your handling code here:
        menunew mn = new menunew();
        utama.removeAll();
        utama.add(mn).setVisible(true);
    }//GEN-LAST:event_pnmenuMouseClicked

    private void pnpesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnpesananMouseClicked
        // TODO add your handling code here:
        PesananBurger pb = new PesananBurger();
        utama.removeAll();
        utama.add(pb).setVisible(true);
    }//GEN-LAST:event_pnpesananMouseClicked

    private void pnpesananMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnpesananMousePressed
        // TODO add your handling code here:
        pnmenu.setBackground(DefaultColor);
        pncust.setBackground(DefaultColor);
        pnpesanan.setBackground(ClickedColor);
        pnpegawai.setBackground(DefaultColor);
        pnmeja.setBackground(DefaultColor);
        pntransaksi.setBackground(DefaultColor);
        pndetailpesanan.setBackground(DefaultColor);
    }//GEN-LAST:event_pnpesananMousePressed

    private void pncustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pncustMouseClicked
        // TODO add your handling code here:
        customers cs = new customers();
        utama.removeAll();
        utama.add(cs).setVisible(true);
    }//GEN-LAST:event_pncustMouseClicked

    private void pncustMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pncustMousePressed
        // TODO add your handling code here:
        pnmenu.setBackground(DefaultColor);
        pncust.setBackground(ClickedColor);
        pnpesanan.setBackground(DefaultColor);
        pnpegawai.setBackground(DefaultColor);
        pnmeja.setBackground(DefaultColor);
        pntransaksi.setBackground(DefaultColor);
        pndetailpesanan.setBackground(DefaultColor);
    }//GEN-LAST:event_pncustMousePressed

    private void pnpegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnpegawaiMouseClicked
        // TODO add your handling code here:
        Pegawai pg = new Pegawai();
        utama.removeAll();
        utama.add(pg).setVisible(true);
    }//GEN-LAST:event_pnpegawaiMouseClicked

    private void pnpegawaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnpegawaiMousePressed
        // TODO add your handling code here:
        pnmenu.setBackground(DefaultColor);
        pncust.setBackground(DefaultColor);
        pnpesanan.setBackground(DefaultColor);
        pnpegawai.setBackground(ClickedColor);
        pnmeja.setBackground(DefaultColor);
        pntransaksi.setBackground(DefaultColor);
        pndetailpesanan.setBackground(DefaultColor);
    }//GEN-LAST:event_pnpegawaiMousePressed

    private void pnmejaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnmejaMouseClicked
        // TODO add your handling code here:
        AdminMeja am = new AdminMeja();
        utama.removeAll();
        utama.add(am).setVisible(true);
    }//GEN-LAST:event_pnmejaMouseClicked

    private void pnmejaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnmejaMousePressed
        // TODO add your handling code here:
        pnmenu.setBackground(DefaultColor);
        pncust.setBackground(DefaultColor);
        pnpesanan.setBackground(DefaultColor);
        pnpegawai.setBackground(DefaultColor);
        pnmeja.setBackground(ClickedColor);
        pntransaksi.setBackground(DefaultColor);
        pndetailpesanan.setBackground(DefaultColor);
    }//GEN-LAST:event_pnmejaMousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void pntransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pntransaksiMouseClicked
        Transaksi2 cs = new Transaksi2();
        utama.removeAll();
        utama.add(cs).setVisible(true);
    }//GEN-LAST:event_pntransaksiMouseClicked

    private void pntransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pntransaksiMousePressed
        // TODO add your handling code here:
        pnmenu.setBackground(DefaultColor);
        pncust.setBackground(DefaultColor);
        pnpesanan.setBackground(DefaultColor);
        pnpegawai.setBackground(DefaultColor);
        pnmeja.setBackground(DefaultColor);
        pntransaksi.setBackground(ClickedColor);
        pndetailpesanan.setBackground(DefaultColor);
    }//GEN-LAST:event_pntransaksiMousePressed

    private void pndetailpesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pndetailpesananMouseClicked
        // TODO add your handling code here:
        DetailPesanan dp = new DetailPesanan();
        utama.removeAll();
        utama.add(dp).setVisible(true);
        
    }//GEN-LAST:event_pndetailpesananMouseClicked

    private void pndetailpesananMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pndetailpesananMousePressed
        // TODO add your handling code here:
        pnmenu.setBackground(DefaultColor);
        pncust.setBackground(DefaultColor);
        pnpesanan.setBackground(DefaultColor);
        pnpegawai.setBackground(DefaultColor);
        pnmeja.setBackground(DefaultColor);
        pntransaksi.setBackground(DefaultColor);
        pndetailpesanan.setBackground(ClickedColor);
    }//GEN-LAST:event_pndetailpesananMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pncust;
    private javax.swing.JPanel pndetailpesanan;
    private javax.swing.JPanel pnmeja;
    private javax.swing.JPanel pnmenu;
    private javax.swing.JPanel pnpegawai;
    private javax.swing.JPanel pnpesanan;
    private javax.swing.JPanel pntransaksi;
    private javax.swing.JPanel utama;
    // End of variables declaration//GEN-END:variables

}
